### ISSUE TITLE
the project now fails to compile , because of using outdated crates 

### ISSUE THREAD

**Issue by GunpowderGuy** [Dooskington/Rustcaster#1]
this compilation error
![screenshot from 2018-05-13 20-58-58](https://user-images.githubusercontent.com/9205622/39974915-32feadb2-56f1-11e8-83b2-9d3489b7aef7.png)
is caused by the rustc serialize version used by rustcaster utilizying deprecated features  ( https://stackoverflow.com/questions/48357712/error-encountered-while-building-trpl-ebook-patterns-arent-allowed-in-methods ), after updating it and the sdl2 image crate ( which also produced a compilation error ) im getting this 
![screenshot from 2018-05-13 21-12-24](https://user-images.githubusercontent.com/9205622/39975128-61784742-56f2-11e8-8c5c-3ca7605c8477.png)

**Comment by Dooskington** [comment]
Hi, thanks a ton for pointing this out. I've updated the repo.

I'm not sure what is causing that linking error of yours, but it's likely related to how you installed SDL2. If the code still doesn't compile, make sure you have followed the instructions here:
https://github.com/Rust-SDL2/rust-sdl2

**Comment by diegor8** [comment]
is this due to a difference in configuration or really another error in the code 

![screenshot from 2018-05-13 20-58-58](https://user-images.githubusercontent.com/9205622/40071036-58a9a806-5835-11e8-91b4-456e0dbb76ec.png)

i have already reinstalled sdl2 as the rust sdl2 repo says i should ( i am using fedora btw ) but i still cat compile rustcaster

**Comment by GunpowderGuy** [comment]
still getting errors 
![screenshot from 2018-05-16 11-53-08](https://user-images.githubusercontent.com/9205622/40131651-2b70fde6-5900-11e8-87d2-121c9fa46860.png)

**Comment by Dooskington** [comment]
Not sure @diegor8, It seems like a problem with the rust toolchain you are trying to use.
I have only tested it on macOS with the latest stable Rust, so I'm not entirely sure what the issue could be.

**Comment by GunpowderGuy** [comment]
@Dooskington after doing a clean install of fedora and the rust tool-chain then verifying that i am using the latest stable version , rustc still refuses to compile without removing the redundant syntaxis , your system probably has additional configuration that makes some warnings be ignored

**Comment by Dooskington** [comment]
@diegor8 Which redundant syntax are you referring to?

I've had it tested on both macOS and linux now, and still cannot reproduce your error. Latest toolchain, stable.

Have you tried running these commands before doing a compile?
`sudo apt-get install libsdl2-dev`
`sudo apt-get install libsdl2-image-dev`
