### ISSUE TITLE
Can I use this in a game?

### ISSUE THREAD

**Issue by violetastcs** [Dooskington/Rustcaster#2]
Just wondering, I will credit you

**Comment by Dooskington** [comment]
Sure.

You'd probably have to tear a lot of it up to fit game logic and do things like sprite collisions, but you can totally use it for a game. I also added a license to the repo just to make it clear that this is freely usable.

**Comment by violetastcs** [comment]
Thanks. And yea I have already begun hacking away at it to fit in game logic, but after I've done that it shouldn't be *too* much different from a top-down shooter.
